### ISSUE TITLE
How to change the shape?

### ISSUE THREAD

**Issue by Junhuan-Peng** [WeskerYuan/flydan#1]
Can you give me a hand with this? 
I want to change the shape of the drone formation,how can I get it?
Thanks！

**Comment by WeskerYuan** [comment]
> Can you give me a hand with this?
I want to change the shape of the drone formation,how can I get it?
Thanks！

You have to first understand that this is a flocking control problem, and the shape of the drone formation is determined by the cost function and its constraints. In this case, it is targeted to form a lattice (or grid), which results in a pentagon under the condition of 5 drones and all-to-all connected topology.
If you want to change the formation to a specific shape or distribution, you'll have to modify the cost funtion and dramatically rewrite the code, I might be of little help here. Sorry for that.
